# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Zakhary Kaplan
email: zakharykaplan@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Homepage of Zakhary Kaplan, Computer Engineering student at the
  University of Toronto. Check out my latest projects or connect with me.
permalink: "/blog/:title"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zakharykaplan.ca" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author:
  name: Zakhary Kaplan # add your name
  img: zakharykaplan.jpeg # add your photo
  about: >- # add an about section
    I am a Computer Engineering student and software developer with a
    passion for exploring the world of computing.

# General settings
general:
  date_format: "%d %b, %Y"

# Social settings
social:
  twitter: # add your Twitter handle
  facebook: # add your Facebook handle
  github: zakharykaplan # add your Github handle
  linkedin: zakharykaplan # add your LinkedIn handle

# Google Analytics
google_analytics: # add your Google Analytics identifier

# Disqus
disqus:
  shortname: # add your Disqus identifier

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

paginate: 8
paginate_path: "/blog/:num"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
# Repo specific excludes
  - CNAME
  - README.md
